php:
  preset: laravel
  disabled:
    - no_unused_imports
  finder:
    not-name:
      - index.php
js:
  finder:
    not-name:
      - webpack.mix.js
css: true
# if (!mix.inProduction()) {
#     mix.browserSync({open:false});
# }
